Sane Opsgenie alerting
vshn/component-appcat pull request #487
Opened 2024-09-23 07:55 UTC by wejdross

PR ensures we have new Opsgenie alerts that self resolve depending on time window, so we keep our Responsible Ops sane. It leaves old logic generated by Sloth tool, but disables forwarding alerts to Opsgenie. 

## Checklist

- [x] The PR has a meaningful title. It will be used to auto generate the
      changelog.
      The PR has a meaningful description that sums up the change. It will be
      linked in the changelog.
- [x] PR contains a single logical change (to build a better changelog).
- [x] Categorize the PR by adding one of the labels:
      `bug`, `enhancement`, `documentation`, `change`, `breaking`, `dependency`
      as they show up in the changelog.
- [x] Link this PR to related issues or PRs.

2024-09-23 09:24 UTC, wejdross commented on component/slos.libsonnet
> +            OnCall: false,
I just increased value for 1 minute to 45 second instead of 12, that should eliminate false positives

2024-09-23 09:24 UTC, wejdross commented on component/vshn_alerting.jsonnet
> +            expr: 'rate(appcat_probes_seconds_count{reason!="success", service="' + serviceName + '", ha="true", maintenance="false"}[5m]) > 0.2 and rate(appcat_probes_seconds_count{reason!="success"
I just increased value for 1 minute to 45 second instead of 12, that should eliminate false positives

2024-09-23 09:25 UTC, wejdross commented on component/vshn_alerting.jsonnet
> +            expr: 'rate(appcat_probes_seconds_count{reason!="success", service="' + serviceName + '", ha="true", maintenance="false"}[5m]) > 0.2 and rate(appcat_probes_seconds_count{reason!="success"
also removed maitenance flag

2024-09-24 11:16 UTC, Kidswiss requested changes
LGTM, but let's wait with approval until you figured out how to disable the opsgenie routing for the sloth alerts.

2024-09-24 14:27 UTC, Kidswiss requested changes
Just one more thing.

2024-09-24 14:27 UTC, Kidswiss commented on component/vshn_alerting.jsonnet
> +              service: serviceName,
You missed the `syn: 'true'` label.

2024-09-25 06:17 UTC, Kidswiss requested changes
Sandro's comment about no runbook is very valid.

We should add a runbook link to the alerts. Especially as these can go to OnCall for people who have never touched AppCat.

2024-09-30 10:54 UTC, Kidswiss approved these changes
LGTM if you haven't seen any false positives anymore.

2024-09-30 11:15 UTC, merged